### ISSUE TITLE
Fatal exception 29(StoreProhibitedCause)

### ISSUE THREAD

**Issue by timvdsm** [danielschramm/esphome#2]
Hi Daniel,
Many thanks for all your hard work.
I am also testing this with an ESP8266 (nodemcu v3) + MCP2515.
In the beginning there was no problem, but now, after adding more code, I receive an error when flashing my esp ...
As I'm capturing the status of all my lights + covers my yaml file is around 750 code lines. See file "fatal exeption.yaml"
I still need to add some cover modules (around 32 relais).

Basically it works like this: 
- my existing (non HA) domotics systems publishes the states of my lights and covers on it's canbus. I want to capture this data and update the status of my corresponding entities in HA. All my lights and covers are connected to relais on modules. 
- the data which I receive on the canbus is always from the same can_id (can_id: 0x2ff01) and as follow: 
   data[0]: module nr
   data[1]: id nr on the module 
   data[2]: status of the ID (00 or 01) 
   the data is in hex format. 
- when this data is received I turn on or off an input_boolean in HA. This input_boolean is then used as a value_template to show the status in HA. 

I have 8 modules (data[0]), with each time 12 relais (ID's) per module (data[1]). This means there are 96 possible relais/entities (combination of data[0] & data[1]). And each relais (entity) can be in status 00 or 01 (data[2]). So for all of theses 96 entities I need to change the status of the HA entity when the data is received on the canbus. 

This is the error I receive when flashing my ESP:

Using ‘COM3’ as serial port.
Connecting…
Detecting chip type… ESP826 %)Writing at 0x00044000… (100 %)Wrote 421520 bytes (285503 compressed) at 0x00000000 in 7.0 seconds (effective 478.3 kbit/s)…
Hash of data verified.

Leaving…
Hard Resetting…
Done! Flashing is complete!

Showing logs:
[13:07:05]
[13:07:05]SDK:2.2.2-dev(38a443e)/Core:2.7.3-3-g2843a5ac=20703003/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
[13:07:05][I][logger:166]: Log initialized
[13:07:05][C][ota:366]: There have been 1 suspected unsuccessful boot attempts.
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:05]Fatal exception 29(StoreProhibitedCause):
[13:07:13]Fa
[13:07:13] ets Jan 8 2013,rst cause:4, boot mode:(3,6)
[13:07:13]
[13:07:13]wdt reset
[13:07:13]load 0x4010f000, len 3584, room 16
[13:07:13]tail 0
[13:07:13]chksum 0xb0
[13:07:13]csum 0xb0
[13:07:13]v2843a5ac
[13:07:13]~ld
[13:07:13]

Is this related to a storage issue on the ESP? Or is there something else you are aware off?

Secondly, I have also made a cleanup of the code (with an additional cover module integrated) that you can find in file "issues.yaml". With this yaml I can flash the ESP8266. So it doesn't give the "Fatal exception 29(StoreProhibitedCause)" error. However it restarts the ESP when receiving data on the canbus which changes the state of a binary_sensor.
Here I use binary_sensor to set the state depending on the data received on the canbus instead of an HA input_boolean. 

I have also attached a 3rd file: working yaml file. This is working perfectly as intended. However not all modules are integrated yet. 

And maybe a last question, as I did not implement this functionality yet. Five of the 96 entities are dimmer lights. So there I receive for data[2] not a 00 or 01 value, but a brightness value in hex. The value x64 is received on the canbus for brightness 100%, x32 for brightness 50%, ... I think the most easiest way is to map this with the brightness_pct value of my dimmer light entity in HA. So i guess I first need to change the received  data[2] value from hex to dec and then set the brightness_pct value to that new value in HA. 
Do you have any idea what would be the best code to do that? 

Many thanks

[Archief.zip](https://github.com/danielschramm/esphome/files/5609311/Archief.zip)
[Working.yaml.zip](https://github.com/danielschramm/esphome/files/5609345/Working.yaml.zip)

**Comment by timvdsm** [comment]
Hi Daniel, 
I saw there was a Review fix part 1 & Review fix part 2 released. I suppose this has nothing to do is with the issue above?

**Comment by danielschramm** [comment]
Hallo @timvdsm,

I just did some tests on "fatal exception.yaml" right now.
The error is a memory protection fault, normally caused by violating array ranges.

In your case I think I can confirm it's really just a memory overflow because of your really huge number of components.
There might just be two possible approaches to resolve it with ESPHome.
1. Try to use a ESP32 instead of an ESP8266 since it has much more resources. I just did not test Canbus with an ESP32 right now.
2. You could split the config to at lease two ESP8266 nodes which cover each some rooms or specific types of devices.

Tests I did to confirm:
Just deleted some entries from the beginning - out of the middle - from the end. And always it started up without issues so the content of the deleted lines cannot be the issue and it has to be the pure count.


To the other questions:
Could you please test them again with really stripped config files only implementing the individual issue and post your results again?
I'm not exactly sure if I understand correctly the issues with the dimmer and the binary sensor and if the issues are just side effects from the memory problem.

Daniel

**Comment by danielschramm** [comment]
> Hi @danielschramm ,
> I saw there was a Review fix part 1 & Review fix part 2 released. I suppose this has nothing to do is with the issue above?

Just cosmetic changes to the code the only functional change for users: "can_ext_id" was replaced by "use_extended_id" in the config file.

**Comment by timvdsm** [comment]
> Hallo @timvdsm,
> 
> I just did some tests on "fatal exception.yaml" right now.

Hi @danielschramm 
Many thanks for your reply. Would an ESP32 be able to handle it all? And is the MCP2515 compatible with esp32 as it seems to have an integrated can controller? Any chance your canbus solution will not work on an esp32?
For me I certainly want to try it, off course if there is a chance it will work. Would you be able to give support on an esp32 implementation?  

Next to that I am also looking to optimize my code. I want to start with an "if condition" for data0 and putt the rest (for data1) under cases. 
As I'm not a specialist in coding, would the code here under work? Or how should I adapt it the best way? 
I receive 3 data on the canbus.
data[0]: x04 (module nr)
data[1]: x00, x01, x02, ... , x0b (id on module)
data[2]: 00 or 01  (status of id)

canbus:
  - platform: mcp2515
    id: my_mcp2515
    spi_id: McpSpi
    cs_pin: GPIO14
    can_id: 4
    #mode: NORMAL
    on_frame:
    - can_id: 0x2ff01
      can_ext_id: true
      then:
        - if:
            condition:
              lambda: 'return x[0] == 0x04;'
            then:
              - lambda: |- switch(x[1]) {
                    case 0x00: {
              		  - lambda: |- switch(x[2]) {
                            case 0x0: id(can_bus_licht_xxxx).publish_state(false); break;
                            case 0x1: id(can_bus_licht_xxxx).publish_state(true); break;
                 		 }; break; 
                    case 0x01:
              		  - lambda: |- switch(x[2]) {
                            case 0x0: id(can_bus_licht_xxxx1).publish_state(false); break;
                            case 0x1: id(can_bus_licht_xxxx1).publish_state(true); break;
                 		 } break;
                    case 0x02:
              		  - lambda: |- switch(x[2]) {
                            case 0x0: id(can_bus_licht_xxxx2).publish_state(false); break;
                            case 0x1: id(can_bus_licht_xxxx2).publish_state(true); break;
                 		 } break;
                    case 0x03:
              		  - lambda: |- switch(x[2]) {
                            case 0x0: id(can_bus_licht_xxxx3).publish_state(false); break;
                            case 0x1: id(can_bus_licht_xxxx3).publish_state(true); break;
                 		 } break;
                    case 0x04:
              		  - lambda: |- switch(x[2]) {
                            case 0x0: id(can_bus_licht_xxxx3).publish_state(false); break;
                            case 0x1: id(can_bus_licht_xxxx3).publish_state(true); break;
                 		 } break;

                    case ....
                  }  

Many thanks for your support.

**Comment by danielschramm** [comment]
MCP 2515 should work with the ESP32 as well.
I'm not sure if all your application will fit, just give it a try.
The internal can controller would be better than an external MCP, but it's currently on lower priority than the MCP which works for both controllers.

**Comment by danielschramm** [comment]
To your code:
`- can_id: 0x2ff01
      can_ext_id: true
      then:
        - if:
`

I would start with - lambda instead of the if and implement all of the rest inside the Lambda.
The code should then be much cleaner.

**Comment by timvdsm** [comment]
> MCP 2515 should work with the ESP32 as well.
> I'm not sure if all your application will fit, just give it a try.
> The internal can controller would be better than an external MCP, but it's currently on lower priority than the MCP which works for both controllers.

Hi, I’ve ordered an esp32-wroom-32 (AZDelivery ESP-32 Dev Kit C V4).  Will have it next week. So I can test. I suppose I can still use in HA supervisor —> esphome_version : ‘danielschramm: canbus’?
Any idea about the wiring? And other things I need to take into account?

**Comment by timvdsm** [comment]
> To your code:
> `- can_id: 0x2ff01 can_ext_id: true then: - if: `
> 
> I would start with - lambda instead of the if and implement all of the rest inside the Lambda.
> The code should then be much cleaner.
I receive 3 datasets on the canbus: data0, data1 & data2. 
Keep ik mind that for data0, I have 8 possible cases. For each of these 8 data0 cases, i have 12 data1 cases. And each of these 12 data1 cases can have status 00 or 01. Status 00 means the state of that specific entity is off and 01 means the state of that specific entity is on.
If I putt everything after the - landa, then I would have 3 nested cases. Is that possible? 
Would it be possible to give me an example syntax for that?

**Comment by danielschramm** [comment]
> > To your code:
> > `- can_id: 0x2ff01 can_ext_id: true then: - if: `
> > I would start with - lambda instead of the if and implement all of the rest inside the Lambda.
> > The code should then be much cleaner.
> 
> I receive 3 datasets on the canbus: data0, data1 & data2.
> Keep ik mind that for data0, I have 8 possible cases. For each of these 8 data0 cases, i have 12 data1 cases. And each of these 12 data1 cases can have status 00 or 01. Status 00 means the state of that specific entity is off and 01 means the state of that specific entity is on.
> If I putt everything after the - landa, then I would have 3 nested cases. Is that possible?
> Would it be possible to give me an example syntax for that?

Hello,

Nested switch statements are not a nice style.
But I see no point why it should not work. It creates a lot of branches.
Using tables of function pointers instead of switch might be more efficient. - seems to be not directly possible in a lambda.

I never did it right now, but perhaps you could create a Generic Custom Component which build up a class and  do the complex stuff.

**Comment by timvdsm** [comment]
In meantime I received my AZ-Delivery ESP-32 Dev Kit C V4 board earlier than expected. Do you have any idea about the wiring to the MCP2515?
And can I still use esphome_version: ‘danielschramm:canbus’ for my esp32 within the supervisor-esphome-configuration tab?
Then I can give it a test :slight_smile:

Many thanks.

<img width="1070" alt="Schermafbeelding 2020-12-06 om 12 07 34" src="https://user-images.githubusercontent.com/14946020/101278453-a1ece100-37bb-11eb-9fa7-1e6b73715e21.png">

**Comment by danielschramm** [comment]
Hello,

I'm just busy with some private TODOs:
![image](https://user-images.githubusercontent.com/7165994/101283445-b55b7480-37da-11eb-90ca-444d7fe131bc.png)

It should directly work with ESP32. 
Perhaps I can also try it later this week and come back with detailed configuration.

Daniel

**Comment by timvdsm** [comment]
Hi @danielschramm 
That would be really great if you could come back with some detailed configuration 😁👍🏻
Many thanks for your support!

**Comment by danielschramm** [comment]
Hello @timvdsm 
I just tested it successfully on a ESP32 with the following GPIOs:

  clk_pin: GPIO18
  mosi_pin: GPIO21
  miso_pin: GPIO22
  cs_pin: GPIO19

Please let me know how many template devices you could get running on the ESP32.

Good Luck,

Daniel

**Comment by timvdsm** [comment]
Hi @danielschramm 
Everything is well connected and I can see all data on the canbus. 
Putting some code now. 

However I see on error .. 
<img width="736" alt="Schermafbeelding 2020-12-10 om 10 19 53" src="https://user-images.githubusercontent.com/14946020/101752262-98bc8680-3ad1-11eb-862f-be34aed5e547.png">

Any idea?  As this was the same code which was working before.

**Comment by timvdsm** [comment]
Hi @danielschramm 
I've connected everything and it works pretty well. 
Also with the esp32 i've reached the maximum templated devices. 
All 6 modules are already working, it's just the last module which is too much and the esp32 crashes when I add the code for this last module :-) 

So I just ordered a 2nd esp32 board and I will spread everything over these 2. So that should work. 
I will test now further with my 6 modules during the next days and I will keep you up to date about the stability. 

A question: for my last module, I need to capture a brightness value on the canbus. It's published under data[2] on the canbus. This value is in hex format, so it is 00 (when light is off) and it's x64 (when brightness is 100%). I need to set the level state of my light in HA to this value when I receive this message. Any idea what would be the ideal code to do that in esphome?

Thanks!

**Comment by danielschramm** [comment]
Merge of this repository into esphome/Dev is now finished. I close this branch.

**Comment by timvdsm** [comment]
Hi @danielschramm 
If I use esphome_version: dev in the configuration page on HA, it gives an error ... 


File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1165, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    
        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        =============================DEBUG ASSISTANCE=============================
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c0s98xej/cryptography/
[15:20:45] FATAL: Failed installing esphome pinned version.
[cont-init.d] 30-esphome.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by timvdsm** [comment]
I can use following branch ... 
esphome_version: 'danielschramm:canbus_extid'

However it seems to have problems:
```
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
...
```
And I don't see anything coming through on the can bus. 

Strange as it worked before without any problems. But then I used: esphome_version: 'danielschramm:canbus'.
However that branch is not available anymore. 

And as mentioned earlier, using esphome_version: dev gives an error installing.

**Comment by danielschramm** [comment]
the esphome/dev works perfekt on my setup.
It was merged from danielschramm:canbus which I deleated after the successfull merge.
can_extid was a temporary branch.

**Comment by timvdsm** [comment]
Seems to be a known error in the dev for certain ARM. I found a turnaround.
However ... I am not able to read the canbus.
When activating level: VERY_VERBOSE, I get following log continuously:

[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...
[14:22:52][VV][spi:016]: Disabling SPI Chip on pin 19...
[14:22:52][VV][spi:095]: Enabling SPI Chip on pin 19...

Any idea what this could be? Something hardware related? 
I used the same config as you mentioned before on my esp32:
clk_pin: GPIO18
mosi_pin: GPIO21
miso_pin: GPIO22
cs_pin: GPIO19

Strange is that it has worked perfectly for me for some weeks... and now it doesn't anymore.

**Comment by danielschramm** [comment]
You enabled very verbose for the SPI Interface and that will give you the chipselect on every data poll between esp and mcp2515.
Seems OK to me.
You should set high log levels only for the component you really need to debug.

**Comment by timvdsm** [comment]
Hi @danielschramm 
Pretty weird, as before everything was working well. 
It' maybe something stupid.
I've used following config for my ESP32: 

```
spi:
  id: McpSpi
  clk_pin: GPIO18
  mosi_pin: GPIO21
  miso_pin: GPIO22

canbus:
  - platform: mcp2515
    id: my_mcp2515
    spi_id: McpSpi
    cs_pin: GPIO19
    can_id: 4
    use_extended_id: True
```

**Comment by danielschramm** [comment]
Please use IDs only with lowercase letters.
I think uppercase was not allowed as ID in esphome.

**Comment by timvdsm** [comment]
Unfortunately that didn't do the trick ... 
I'm using this version:
esphome_version: 9cff0f38981efa780938e6c69d1427b14381b167
https://github.com/esphome/esphome/pull/1384/commits/9cff0f38981efa780938e6c69d1427b14381b167
I'm using this commit as the official dev version is giving a known error. This commit is the latest I can install without an error. 

Was there anything else changed except for the use_extended_id: true instead of the can_ext_id: true.
I suppose nothing else was changed in the new version? 
I'm about to tearing my hair out :-) 

```
INFO Reading configuration /config/esphome/dobiss2_esp32.yaml...
INFO Starting log output from dobiss2_esp32.local using esphome API
INFO Connecting to dobiss2_esp32.local:6053 (192.168.x.xxx)
INFO Successfully connected to dobiss2_esp32.local
[21:09:04][I][app:105]: ESPHome version 1.16.0-dev compiled on Jan  4 2021, 14:17:05
[21:09:04][C][wifi:443]: WiFi:
[21:09:04][C][wifi:303]:   SSID: 'esp32'[redacted]
[21:09:04][C][wifi:304]:   IP Address: 192.168.x.xxx
[21:09:04][C][wifi:306]:   BSSID: 80:3F:5D:5D:AF:4B[redacted]
[21:09:04][C][wifi:307]:   Hostname: 'dobiss2_esp32'
[21:09:04][C][wifi:311]:   Signal strength: -43 dB ▂▄▆█
[21:09:04][V][wifi:313]:   Priority: 0.0
[21:09:04][C][wifi:315]:   Channel: 11
[21:09:04][C][wifi:316]:   Subnet: 255.255.255.0
[21:09:04][C][wifi:317]:   Gateway: 192.168.x.x
[21:09:04][C][wifi:318]:   DNS1: 192.168.x.xxx
[21:09:04][C][wifi:319]:   DNS2: 0.0.0.0
[21:09:04][C][spi:081]: SPI bus:
[21:09:04][C][spi:082]:   CLK Pin: GPIO18 (Mode: OUTPUT)
[21:09:04][C][spi:083]:   MISO Pin: GPIO22 (Mode: INPUT)
[21:09:04][C][spi:084]:   MOSI Pin: GPIO21 (Mode: OUTPUT)
[21:09:04][C][spi:085]:   Using HW SPI: YES
[21:09:04][C][uptime.sensor:030]: Uptime Sensor 'ESP Uptime 2'
[21:09:04][C][uptime.sensor:030]:   Unit of Measurement: 's'
[21:09:04][C][uptime.sensor:030]:   Accuracy Decimals: 0
[21:09:04][C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[21:09:04][V][uptime.sensor:030]:   Unique ID: '240ac45fee30-uptime'
[21:09:04][C][template.sensor:021]: Template Sensor 'Uptime Days 2'
[21:09:04][C][template.sensor:021]:   Unit of Measurement: 'days'
[21:09:04][C][template.sensor:021]:   Accuracy Decimals: 1
[21:09:04][C][template.sensor:021]:   Icon: 'mdi:clock-start'
[21:09:04][C][template.sensor:022]:   Update Interval: 60.0s
[21:09:04][C][canbus:019]: config extended id=0x00000004
[21:09:04][C][logger:185]: Logger:
[21:09:04][C][logger:186]:   Level: VERBOSE
[21:09:04][C][logger:187]:   Log Baud Rate: 115200
[21:09:04][C][logger:188]:   Hardware UART: UART0
[21:09:04][C][captive_portal:169]: Captive Portal:
[21:09:04][C][ota:029]: Over-The-Air Updates:
[21:09:04][C][ota:030]:   Address: dobiss2_esp32.local:3232
[21:09:04][C][ota:032]:   Using Password.
[21:09:04][C][api:095]: API Server:
[21:09:04][C][api:096]:   Address: dobiss2_esp32.local:6053
[21:09:04][C][wifi_signal.sensor:009]: WiFi Signal 'ESP WiFi Signal 2'
[21:09:04][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dB'
[21:09:04][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[21:09:04][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[21:09:04][V][wifi_signal.sensor:009]:   Unique ID: '240ac45fee30-wifisignal'
```
Anything which looks weird in your understanding ... ?

**Comment by danielschramm** [comment]
Could you attach your whole config file and a complete log please.

**Comment by timvdsm** [comment]
@danielschramm 
many thanks for your support!

In attachment the requested files. 

[ESPhome logs.zip](https://github.com/danielschramm/esphome/files/5769515/ESPhome.logs.zip)

**Comment by danielschramm** [comment]
Why did you set "esphome_version: 9cff........" ?
I just use "esphome_version: dev"

**Comment by timvdsm** [comment]
Hi @danielschramm 
That's because the esphome_version: dev gives an error when installing. 
It seems to be a known error:
https://github.com/esphome/issues/issues/1702#issuecomment-749720677

As mentioned in my earlier post: 

> Hi @danielschramm
> If I use esphome_version: dev in the configuration page on HA, it gives an error ...
> 
> ```
> File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1165, in run_setup
>         raise DistutilsError("Setup script exited with %s" % (v.args[0],))
>     distutils.errors.DistutilsError: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
> 
>     
>         =============================DEBUG ASSISTANCE=============================
>         If you are seeing a compilation error please try the following steps to
>         successfully install cryptography:
>         1) Upgrade to the latest pip and try again. This will fix errors for most
>            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>         2) Read https://cryptography.io/en/latest/installation.html for specific
>            instructions for your platform.
>         3) Check our frequently asked questions for more information:
>            https://cryptography.io/en/latest/faq.html
>         =============================DEBUG ASSISTANCE=============================
>     
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c0s98xej/cryptography/
> [15:20:45] FATAL: Failed installing esphome pinned version.
> [cont-init.d] 30-esphome.sh: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
> 
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> ```

Workaround is to specify the exact version. 
This one is the last commit which can be installed on my rasp pi and doesn't give the above error. 
https://github.com/esphome/esphome/commit/9cff0f38981efa780938e6c69d1427b14381b167
